apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.yara.name }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
    component: {{ .Values.yara.name }}-{{ .Values.environment }}
  ports:
    - name: http
      port: {{ .Values.yara.service.port }}
      targetPort: http
      protocol: TCP
