apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
  name: {{ .Values.name }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 3600
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      environment: {{ .Values.environment }}
      type: website
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        environment: {{ .Values.environment }}
        type: website
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: speed
                operator: NotIn
                values:
                - fast
            weight: 1
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: http-management
          containerPort: 8081
          protocol: TCP
        env:
        - name: DEPLOYMENT_CONFIG
          value: /run/secrets/open-vsx.org/deployment/configuration.yml
        - name: ENVNAME
          value: {{ .Values.environment }}
        - name: JVM_ARGS
          value: {{ .Values.website.jvmArgs }}
        volumeMounts:
        - name: deployment-configuration
          mountPath: /run/secrets/open-vsx.org/deployment
        - name: truststore-with-elasticsearch-certs
          mountPath: /run/secrets/open-vsx.org/truststore
        envFrom:
        - secretRef:
            name: grafana-cloud-secret-{{ .Values.environment }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: http-management
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /actuator/health/readiness
            port: http-management
          periodSeconds: 10
        startupProbe:
          failureThreshold: 360
          httpGet:
            path: /actuator/health/readiness
            port: http-management
          periodSeconds: 10
          initialDelaySeconds: 30
      initContainers:
      - command:
        - sh
        - -c
        - keytool -import -noprompt -alias es-http-certs-internal -file /run/secrets/elasticsearch/http-certs/ca.crt -storetype jks -storepass 'changeit' -keystore /run/secrets/open-vsx.org/truststore/elasticsearch-http-certs.keystore
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        name: init-keystore
        volumeMounts:
        - mountPath: /run/secrets/elasticsearch/http-certs
          name: elastic-internal-http-certificates
        - mountPath: /run/secrets/open-vsx.org/truststore
          name: truststore-with-elasticsearch-certs
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: open-vsx-org
            environment: {{ .Values.environment }}
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      volumes:
      - name: deployment-configuration
        secret:
          defaultMode: 420
          optional: false
          secretName: deployment-configuration-{{ .Values.environment }}
      - name: elastic-internal-http-certificates
        secret:
          defaultMode: 420
          optional: false
          secretName: elasticsearch-{{ .Values.environment }}-es-http-certs-internal
      - name: truststore-with-elasticsearch-certs
        emptyDir:
          medium: Memory
