{{- if .Values.eks.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
  name: {{ .Values.name }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.host }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip 
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:365555376529:certificate/c247a8c7-31fa-4116-bd4a-c1e5aebad840
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    {{- if .Values.ingress.wafv2Arn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.wafv2Arn | quote }}
    {{- end }}
spec:
 ingressClassName: alb
 rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: {{ .Values.name }}-{{ .Values.environment }}
           port:
            number: {{ .Values.service.port }}
{{- if eq .Values.environment "eks-production" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
  name: {{ .Values.name }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.host }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip 
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:365555376529:certificate/c247a8c7-31fa-4116-bd4a-c1e5aebad840
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    {{- if .Values.ingress.wafv2Arn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.wafv2Arn | quote }}
    {{- end }}
spec:
 ingressClassName: alb
 rules:
  - host: www.{{ .Values.host }}
    http:
     paths:
      - path: /
        pathType: Prefix
        backend:
         service:
          name: {{ .Values.name }}-{{ .Values.environment }}
          port:
           number: {{ .Values.service.port }}
{{- end }}
{{- end }}