apiVersion: v2
name: openvsx
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: "1.16.0"
dependencies:
  - name: alloy
    version: 1.1.2
    repository: https://grafana.github.io/helm-charts
  - name: bitnami
    version: 18.1.13
    repository: https://charts.bitnami.com/bitnami
    condition: eks.enabled
  - name: aws-load-balancer-controller
    version: 1.14.0
    repository: https://aws.github.io/eks-charts
    condition: eks.enabled